server:
  port: 3001

spring:
  application:
    name: eon-user

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    
  sql:
    init:
      #      mode: always
      mode: never
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql

  cloud:
    nacos:
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}
      discovery:
        server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}

  config:
    import:
      - optional:nacos:application-${spring.profiles.active:dev}.yml
      - optional:nacos:${spring.application.name}-${spring.profiles.active:dev}.yml
# 日志配置
logging:
  level:
    com.eon.user: DEBUG

eon:
  datasource:
    enabled: true
    primary: master
    targets:
      master:
        url: jdbc:mysql://${USER_MYSQL_HOST:${MYSQL_HOST:localhost}}:${USER_MYSQL_PORT:${MYSQL_PORT:3306}}/${USER_MYSQL_DATABASE:${MYSQL_DATABASE:eon}}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
        username: ${USER_MYSQL_USERNAME:${MYSQL_USERNAME:root}}
        password: ${USER_MYSQL_PASSWORD:${MYSQL_PASSWORD:root}}
        driver-class-name: ${USER_MYSQL_DRIVER:${MYSQL_DRIVER:com.mysql.cj.jdbc.Driver}}
  feign:
    log-level: BASIC
  demo:
    echo-url: http://localhost:${server.port}
    mock-enabled: true

